version: '3.7'

services:
  router:
    container_name: tdc.platform.router
    image: tdc.platform.router
    depends_on:
      - gateway
      - landingpage
    build:
      context: platform/router
    ports:
      # Listening port
      - '443:443'
      # Administrator/metrics port
      - '9090:9090'
    volumes:
      - ./platform/router/envoy.yml:/etc/envoy/envoy.yml
      - ./platform/router/ssl:/etc/ssl

  landingpage:
    container_name: tdc.platform.landingpage
    image: nginx:1.20.1-alpine
    networks:
      default:
        aliases:
          - landinpage.tdc.demo.local
    healthcheck:
      test: ['CMD-SHELL', 'wget -O /dev/null http://localhost || exit 1']
      timeout: 3s
      retries: 3

  idp-dex:
    container_name: tdc.platform.idp-dex
    image: sticksnleaves/dex:2.9
    command: dex serve /etc/dex/dex.yml
    ports:
      - 5556:5556
    networks:
      default:
        aliases:
          - dex.tdc.demo.local
    volumes:
      - ./platform/dex/config/:/etc/dex/
      - ./platform/dex/templates/password.html:/go/src/github.com/coreos/dex/web/templates/password.html
    healthcheck:
      test: curl --fail --insecure https://localhost:5556/dex/healthz || exit 1
      interval: 10s
      timeout: 3s
      retries: 3

  gateway:
    container_name: tdc.digihero.gateway
    image: tdc.digihero.gateway
    depends_on:
      - oauth2-proxy
      - dummy-api
      - frontend
    build:
      context: apps/digihero/services/gateway
    networks:
      default:
        aliases:
          - digihero.gateway.apps.internal
    ports:
      # Administrator/metrics port
      - '9999:9999'
    env_file:
      - apps/digihero/env/.env.gateway
    volumes:
      - ./apps/digihero/services/gateway/envoy.template.yml:/envoy.template.yml

  oauth2-proxy:
    container_name: tdc.digihero.oauth2-proxy
    depends_on:
      - idp-dex
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.1.2-amd64
    networks:
      default:
        aliases:
          - digihero.oauth2-proxy.apps.internal
    expose:
      - '8080'
    env_file:
      - apps/digihero/env/.env.oauth2-proxy
      - apps/digihero/env/.env.secrets
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--quiet',
          '--tries=1',
          '--spider',
          'http://localhost:8080/ping',
        ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 90s

  frontend:
    stdin_open: true
    container_name: tdc.digihero.frontend
    image: tdc.digihero.frontend
    build:
      context: .
      dockerfile: ./apps/digihero/services/frontend/Dockerfile
    networks:
      default:
        aliases:
          - digihero.frontend.apps.internal
    volumes:
      - ./apps/digihero/services/frontend:/var/app
      - /apps/digihero/services/frontend/node_modules/

  dummy-api:
    container_name: tdc.digihero.dummy-api
    image: tdc.digihero.dummy-api
    build:
      context: .
      dockerfile: apps/digihero/services/dummy-api/Dockerfile
      target: build
    command: dotnet watch --project services/dummy-api/dummy-api.csproj run
    networks:
      default:
        aliases:
          - digihero.dummy-api.apps.internal
    volumes:
      - ./apps/digihero/services/dummy-api/:/app/services/dummy-api/
      - /app/services/dummy-api/obj/
      - /app/services/dummy-api/bin/
