version: "3.7"

services:
  gateway:
    container_name: tdc.gateway
    image: tdc.gateway
    depends_on:
      - oauth2-proxy
      - dummy-backend
    build:
      context: services/gateway
    networks:
      default:
        aliases:
          - gateway.apps.internal
    ports:
      - "8080:8080"
      - "9090:9090"
    env_file:
      - env/.env.gateway
    volumes:
      - ./src/services/gateway/envoy.template.yml:/envoy.template.yml

  oauth2-proxy:
    container_name: tdc.oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.1.2-amd64
    networks:
      default:
        aliases:
          - oauth2-proxy.apps.internal
    expose:
      - "8080"
    env_file:
      - env/.env.oauth2-proxy

  dummy-backend:
    container_name: tdc.dummy-backend
    image: tdc.dummy-backend
    build:
      context: .
      dockerfile: services/dummy-backend/Dockerfile
      target: build
    command: dotnet watch --project services/dummy-backend/dummy-backend.csproj run
    ports:
      - "4000:8080"
      - "4001:9090"
    networks:
      default:
        aliases:
          - dummy-backend.apps.internal
    volumes:
      - ./services/dummy-backend/:/app/services/dummy-backend/
      # these are required to exclude these folders from mounting
      # they are needed to be local within the container
      - /app/services/dummy-backend/obj/
      - /app/services/dummy-backend/bin/
