version: "3.7"

services:
  gateway:
    depends_on:
      - dummy-backend
    build:
      context: services/gateway
    networks:
      default:
        aliases:
          - gateway.apps.internal
    ports:
      - "8080:8080"
      - "9090:9090"
    env_file:
      - env/.env.gateway
    volumes:
      - ./src/services/gateway/envoy.template.yml:/envoy.template.yml
  dummy-backend:
    container_name: dummy-backend
    image: dummy-backend
    build:
      context: .
      dockerfile: services/dummy-backend/Dockerfile
      target: build
    command: dotnet watch --project services/dummy-backend/dummy-backend.csproj run
    ports:
      - "4000:8080"
      - "4001:9090"
    networks:
      default:
        aliases:
          - dummy-backend.apps.internal
    volumes:
      - ./services/dummy-backend/:/app/services/dummy-backend/
      # these are required to exclude these folders from mounting
      # they are needed to be local within the container
      - /app/services/dummy-backend/obj/
      - /app/services/dummy-backend/bin/
