version: "3.7"

services:
  router:
    container_name: tdc.router
    image: tdc.router
    depends_on:
      - gateway
    build:
      context: platform/router
    ports:
      - "443:443"
      - "9090:9090"
    volumes:
      - ./platform/router/envoy.yml:/etc/envoy/envoy.yml
      - ./platform/router/ssl:/etc/ssl

  gateway:
    container_name: tdc.gateway
    image: tdc.gateway
    depends_on:
      - oauth2-proxy
      - dummy-backend
    build:
      context: apps/digihero/services/gateway
    networks:
      default:
        aliases:
          - gateway.apps.internal
    ports:
      - "8888:8080"
      - "9999:9090"
    env_file:
      - env/.env.gateway
    volumes:
      - ./apps/digihero/services/gateway/envoy.template.yml:/envoy.template.yml

  oauth2-proxy:
    container_name: tdc.oauth2-proxy
    depends_on:
      - dex
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.1.2-amd64
    networks:
      default:
        aliases:
          - oauth2-proxy.apps.internal
    expose:
      - "8080"
    env_file:
      - env/.env.oauth2-proxy
      - env/.env.secrets

  dex:
    container_name: tdc.dex
    image: sticksnleaves/dex:2.9
    command: dex serve /etc/dex/dex.yml
    ports:
      - 5556:5556
    volumes:
      - ./platform/dex/config/:/etc/dex/
      - ./platform/dex/templates/password.html:/go/src/github.com/coreos/dex/web/templates/password.html
    healthcheck:
      test: curl --fail --insecure https://localhost:5556/dex/healthz || exit 1
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      default:
        aliases:
          - dex.tdc.demo.local

  dummy-backend:
    container_name: tdc.dummy-backend
    image: tdc.dummy-backend
    build:
      context: .
      dockerfile: apps/digihero/services/dummy-backend/Dockerfile
      target: build
    command: dotnet watch --project services/dummy-backend/dummy-backend.csproj run
    ports:
      - "4000:8080"
      - "4001:9090"
    networks:
      default:
        aliases:
          - dummy-backend.apps.internal
    volumes:
      - ./apps/digihero/services/dummy-backend/:/app/services/dummy-backend/
      - /app/services/dummy-backend/obj/
      - /app/services/dummy-backend/bin/
